project:
  type: website
  output-dir: docs

website:
  title: "Yimiao Yuan"
  site-url: "https://yimiaoyuan.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contact.qmd
      - text: "CV"
        href: pdfs/cv-Yimiao_Yuan.pdf
      - icon: envelope
        href: "mailto:yymlinda.yuan@mail.utoronto.ca"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



